name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - run: npm ci
    - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Biome check
      run: npm run check
    - name: Run Biome lint
      run: npm run lint
    
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run secretlint
      run: npx secretlint "**/*"